develop init
IlhovVladyslav/autocomplete pull request #1
Opened 2020-04-01 16:00 UTC by IlhovVladyslav

2020-04-02 08:57 UTC, Boikov requested changes

2020-04-02 08:57 UTC, Boikov commented on src/js/app.js
> +let lastChangeCountry = 'Enter country...';
Эта строка может динамически меняться? Не думаю) Тогда нужно использовать const, а не let, всегда когда у тебя переменная постоянна юзай const

2020-04-02 08:57 UTC, Boikov commented on src/js/app.js
> +const defaulValues = () => {
Зачем тебе вообще работать с высотой меню дропдауна? Это не нужно даже для инфинит скролла, у тебя просто должен быть лист и в него динамически должны добавляться элементы, и на этом всё) Никакие высоты менять не нужно для этого

2020-04-02 08:57 UTC, Boikov commented on src/js/app.js
> +    const localStorageValues = local.map((el) => el.name);
Можешь сразу деструктуризировать в аргументах, то есть local.map(({ name }) => name)

2020-04-02 08:57 UTC, Boikov commented on src/js/app.js
> +    await countries.map((el) => !localStorageValues.includes(el.name) ? el : el['viewed'] = true);
Зачем тут await? Это же не асинхронная операция)

2020-04-02 08:57 UTC, Boikov commented on src/js/app.js
> +    await countries.map((el) => !localStorageValues.includes(el.name) ? el : el['viewed'] = true);
И зачем тут el['viewed'], почему не просто el.viewed?)

2020-04-02 08:57 UTC, Boikov commented on src/js/app.js
> +    await countries.map((el) => !localStorageValues.includes(el.name) ? el : el['viewed'] = true);
И вообще так делать нельзя, ты мутируешь в map-функции, она для того и создана чтобы не мутировать. У тебя здесь должно быть (el) => !localStorageValues.includes(el.name) ? el : {...el, viewed: true}

2020-04-02 08:57 UTC, Boikov commented on src/js/app.js
> +    await countries.map((el) => !localStorageValues.includes(el.name) ? el : el['viewed'] = true);
Вообще старайся всегда избегать мутаций по возможности, это очень плохо и вызывает непредвиденные ошибки в будущем

2020-04-02 08:57 UTC, Boikov commented on src/js/app.js
> +      const otherCountries = countries.filter((el) => !(localStorageValues.includes(el.name)));
Зачем обернул в скобки проверку? И деструктуризируй name

2020-04-02 08:57 UTC, Boikov commented on src/js/app.js
> +const showLocalData = () => {
Нет необходимости создавать отдельную функцию, если это всё равно используется только один раз

2020-04-02 08:57 UTC, Boikov commented on src/js/app.js
> +};
Для чего нужна эта функция? Очень странная реализация, сравнивать по tagName что-либо очень опасно.

2020-04-02 08:57 UTC, Boikov commented on src/js/app.js
> +btnClearInput.addEventListener('click', () => clearInput());
Зачем оборачивать в ещё одну функцию? Просто ('click', clearInput)

2020-04-02 08:57 UTC, Boikov commented on src/js/autocopmlete.js
> +        return htmlViewedRusult.push(`
Плохая реализация, мало того что мутируешь, так ещё и возвращаешь push)) Для таких сценариев ты должен использовать метод reduce - он позволит избежать создания лишних переменных и сделает всё красиво

2020-04-02 08:57 UTC, Boikov commented on src/js/countryCard.js
> +  const viewedCountry = await allCountryInfo;
Во-первых - такая строка не имеет смысла, ты просто поставил await перед переменной) await ставится исключительно перед асинхронными операциями чтобы следующая строка дожидалась её завершения и асинхронный код выглядел как синхронный

2020-04-02 08:57 UTC, Boikov commented on src/js/countryCard.js
> +  const viewedCountry = await allCountryInfo;
Во-вторых - если хочешь скопировать массив, а не получить на него ссылку - делай const viewedCountry = [...allCountryInfo]

2020-04-02 08:57 UTC, Boikov commented on src/js/countryCard.js
> +  localData.setdata(...viewedCountry);
Очень странная запись, ты же раскладываешь массив, у тебя все элементы разложатся по отдельным и засетится не понятно что, тут нужно делать setData(viewedCountry) просто

2020-04-02 08:57 UTC, Boikov commented on src/js/countryCard.js
> +  return countryCardTepmlate(...allCountryInfo);
и тут тоже самое, должно быть (allCountryInfo), переделай под такую реализацию, потому что раскладывать массив прям в аргументы это плохо

2020-04-02 08:57 UTC, Boikov commented on src/js/debounce.js
> +export default function debounce(f, ms) {
Нам не нужен свой debounce, просто установи библиотеку (а точнее саб-либу) lodash.debounce и юзай его) Заодно с зависимостями поиграешься

2020-04-02 08:57 UTC, Boikov commented on src/js/localData.js
> +  setdata: (viewedCounries) => {
Все методы должны быть в кэмелкейсе, getData, clearData, setData

2020-04-02 08:57 UTC, Boikov commented on src/js/localData.js
> +    if (localStorage.getItem('viewedCountries') === null) {
Зачем сравнивать с null? Можно просто !localStorage.getItem('viewedCountries')

2020-04-02 08:57 UTC, Boikov commented on src/js/localData.js
> +      const unviewedCountries = JSON.parse(localStorage.getItem('viewedCountries')).filter((item) => item.name !== viewedCounries.name);
name деструктуризируй в фильтре

2020-04-02 08:57 UTC, Boikov commented on src/js/request.js
> +    const result = await fetch(`https://restcountries.eu/rest/v2/${type}/${requestValue}`);
всегда отделяй const-блоки пустыми строками

2020-04-04 10:40 UTC, IlhovVladyslav commented on src/js/app.js
> +let lastChangeCountry = 'Enter country...';
вообще убрал эту переменную

2020-04-04 10:41 UTC, IlhovVladyslav commented on src/js/app.js
> +    const localStorageValues = local.map((el) => el.name);
так и сделал

2020-04-04 10:42 UTC, IlhovVladyslav commented on src/js/app.js
> +    await countries.map((el) => !localStorageValues.includes(el.name) ? el : el['viewed'] = true);
полностью переписал эту часть

2020-04-04 10:43 UTC, IlhovVladyslav commented on src/js/app.js
> +      const otherCountries = countries.filter((el) => !(localStorageValues.includes(el.name)));
убрал скобку, деструктуризировал name

2020-04-04 10:43 UTC, IlhovVladyslav commented on src/js/app.js
> +const showLocalData = () => {
убрал showLocalData как отдельную функцию

2020-04-04 10:45 UTC, IlhovVladyslav commented on src/js/app.js
> +};
удалил эту часть кода, вместо нее просто повесил обработки кликов

2020-04-04 10:46 UTC, IlhovVladyslav commented on src/js/app.js
> +btnClearInput.addEventListener('click', () => clearInput());
исправил

2020-04-04 10:48 UTC, IlhovVladyslav commented on src/js/autocopmlete.js
> +        return htmlViewedRusult.push(`
удалил эту часть кода, реализовал компонент по-другому

2020-04-04 10:49 UTC, IlhovVladyslav commented on src/js/countryCard.js
> +  const viewedCountry = await allCountryInfo;
исправил

2020-04-04 10:50 UTC, IlhovVladyslav commented on src/js/countryCard.js
> +  localData.setdata(...viewedCountry);
исправил

2020-04-04 10:50 UTC, IlhovVladyslav commented on src/js/countryCard.js
> +  return countryCardTepmlate(...allCountryInfo);
исправил

2020-04-04 10:52 UTC, IlhovVladyslav commented on src/js/debounce.js
> +export default function debounce(f, ms) {
подключил lodash.debounce вместо своего debounce

2020-04-04 10:52 UTC, IlhovVladyslav commented on src/js/localData.js
> +  setdata: (viewedCounries) => {
исправил

2020-04-04 10:52 UTC, IlhovVladyslav commented on src/js/localData.js
> +    if (localStorage.getItem('viewedCountries') === null) {
исправил

2020-04-04 10:52 UTC, IlhovVladyslav commented on src/js/localData.js
> +      const unviewedCountries = JSON.parse(localStorage.getItem('viewedCountries')).filter((item) => item.name !== viewedCounries.name);
исправил

2020-04-04 10:54 UTC, IlhovVladyslav commented on src/js/request.js
> +    const result = await fetch(`https://restcountries.eu/rest/v2/${type}/${requestValue}`);
исправил во всем проекте

2020-04-04 12:48 UTC, IlhovVladyslav commented on src/js/app.js
> +const defaulValues = () => {
написал другую реализацию

2020-04-07 07:59 UTC, Boikov approved these changes

2020-04-07 08:34 UTC, merged